name = "backend"
compatibility_date = "2023-12-01"

[vars]
DATABASE_URL="prisma://accelerate.prisma-data.net/?api_key=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhcGlfa2V5IjoiMTM5YmFhMTEtYTdjNS00MzBjLWFhNTktODhiZTVhZDg1MjViIiwidGVuYW50X2lkIjoiMjJhOTYzNDRmZmFjMzJmYzQ4MTQzOWMyMzY1ZmM2Mzg3ZWM3MjI5M2MyMzUzNWE0OTFiYmQxMzU1ZjBjOTcyZCIsImludGVybmFsX3NlY3JldCI6IjI3YWY4OTU3LTFjMzQtNDBjMS1iM2U0LTY0MjY4OGJkYzdkNyJ9.mvw-TVzdVRhjytIfqeRpV1-11IMPKP8q4o77uUfcFnY"
JWT_SECRET = "asdasdasd"




